###################################
### Xiaomi Vaccum Switches
###################################


- platform: template
  switches:
    vacuum:
      friendly_name: Vacuum
      value_template: "{{ is_state('xiaomi_vacuum_cleaner', 'on') }}"
      turn_on:
        service: vacuum.turn_on
        entity_id: vacuum.xiaomi_vacuum_cleaner
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.xiaomi_vacuum_cleaner
