- id: '1640705223252'
  alias: Livingroom Shade Down
  description: Livingroom shade down when dark and cold
  trigger:
  - platform: sun
    event: sunset
    offset: +00:30:00
  condition:
  - condition: numeric_state
    entity_id: weather.dark_sky
    attribute: temperature
    below: '14'
  action:
  - device_id: a34bd909df8d48d18822c3868da4ad1b
    domain: cover
    entity_id: cover.springs_window_fashions_graber_csz1_cellular_shade_switch_3
    type: close
  mode: single
- id: '1640799254299'
  alias: Livingroom Shade Up
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
  condition: []
  action:
  - device_id: a34bd909df8d48d18822c3868da4ad1b
    domain: cover
    entity_id: cover.springs_window_fashions_graber_csz1_cellular_shade_switch_3
    type: open
  mode: single
- id: '1640799316743'
  alias: Office Shade Up 30%
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
  condition: []
  action:
  - device_id: 08d91c0aa95641f8a67ec945831bcbd1
    domain: cover
    entity_id: cover.springs_window_fashions_graber_csz1_cellular_shade_level_2
    type: set_position
    position: 30
  mode: single
- id: '1640799427257'
  alias: Office Shade Up
  description: ''
  trigger:
  - platform: time
    at: '11:00:00'
  condition: []
  action:
  - device_id: 08d91c0aa95641f8a67ec945831bcbd1
    domain: cover
    entity_id: cover.springs_window_fashions_graber_csz1_cellular_shade_switch_2
    type: open
  mode: single
