homeassistant:
  # Name of the location where Home Assistant is running
  name: Alto Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  # Customize the name of the devices
  customize: !include custom_names.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

#Interface design - Lovelace from Yaml
lovelace:
 mode: yaml


# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  #api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret hass_base_url
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

#Recorded data purge intervall
recorder:
  db_url: !secret homeassistant_db
  purge_keep_days: 60

#System health API
system_health:

# Track the sun
sun:

#August lock
august:
  login_method: phone
  username: !secret august_user
  password: !secret august_pass

#Wemo config
wemo:
  static:
    - !secret wemo_mini_ip
    - !secret wemo_mini2_ip

# Home Assistant log
logger:
  default: warning


# Weather
weather:
  - platform: darksky
    api_key: !secret darksky


# Nest config
nest:
  client_id: !secret nestclientid
  client_secret: !secret nestclientsecret

# Philips Hue Lights
hue:
  bridges:
    - host: !secret hueip
      allow_unreachable: true
      allow_hue_groups: true

# ZHA - Zigbee ZWave integration
zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key


# Eight Smart Mattress
eight_sleep:
  username: !secret eightuser
  password: !secret eightpass
  partner: true

#Media players config
media_player:
    - platform: plex
      show_all_controls: true
      use_episode_art: true

#Presence detection
mqtt:
  broker: !secret mqttip
  port: !secret mqttport
  client_id: home-assistant
  keepalive: 60
  username: !secret mqttusername
  password: !secret mqttpassword
  protocol: 3.1


# HTML5 Push Notifications
notify:
  - platform: html5
    name: html5_push_notifications
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email


#Cloud Integration
cloud:
  !include alexa/alexa_cloud.yaml

#Speedtest Configuration
speedtestdotnet:
  scan_interval:
    hours: 1
  monitored_conditions:
    - ping
    - download
    - upload


#Device Tracker
device_tracker:
  - platform: mqtt_json
    devices:
      TiszaPhone: zanzito/TiszaPhone/location
  - platform: mqtt_json
    devices:
      ViviPhone: zanzito/ViviPhone/location


zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 300
  icon: mdi:home

zone 2:
  name: Chopra
  latitude: !secret worklatitude
  longitude: !secret worklongitude
  radius: 500
  icon: mdi:auto-fix

zone 3:
  name: Dog Park
  latitude: !secret dogparklatitude
  longitude: !secret dogparklongitude
  radius: 500
  icon: mdi:bone

# Monitor the proximity of devices to a particular zone and the direction of travel.

proximity:
  home:
    devices:
      - device_tracker.viviphone
      - device_tracker.tiszaphone
    tolerance: 50
    unit_of_measurement: mi

#Xiaomi Vaccum Integration

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

# #Jinvoo Smart devices
#
# tuya:
#   username: !secret tuya_username
#   password: !secret tuya_pass
#   country_code: 1


#Rachio Controller
rachio:
  api_key: !secret rachio-token
  manual_run_mins: 5


# Rachio iFrame Module
panel_iframe:
  rachio:
    title: Rachio
    url: "https://app.rach.io"
    icon: mdi:water-pump

# Text to speech
tts:
  platform: google_translate
  cache: true
  cache_dir: !secret tts_cache_dir
  time_memory: 43200

# Shell Commands
shell_command:
  tank_poweroff: !secret tank_poweroff
  snapshot_frontdoor_gif: convert -loop 0 -delay 100 /home/homeassistant/.homeassistant/www/tmp/frontdoor1.png /home/homeassistant/.homeassistant/www/tmp/frontdoor2.png /home/homeassistant/.homeassistant/www/tmp/frontdoor3.png /home/homeassistant/.homeassistant/www/tmp/a.gif

input_boolean: !include_dir_merge_named input_boolean
input_number: !include_dir_merge_named input_numbers
switch: !include_dir_merge_list switches
light: !include_dir_merge_list  mqttlights
group: !include_dir_merge_named groups
scene: !include_dir_merge_list scenes
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
alexa: !include alexa/alexa.yaml
intent_script: !include alexa/intent_scripts.yaml
script: !include_dir_merge_named scripts
camera: !include cameras/cameras.yaml
