
###########################
### LOVELACE CONFIGURATION
###########################


##############
### RESOURCES - moved to configuration.yaml at 4/21/2020 because version 0.107 deprecated from here
##############
#
#
# resources:
#   - url: /local/mini-graph-card-bundle.js?v=0.9.2 # https://github.com/kalkih/mini-graph-card/releases/tag/v0.9.2
#     type: module
#   - url: /local/button-card.js #?????? https://github.com/custom-cards/button-card
#     type: module
#   - url: /local/slider-entity-row.js # https://github.com/thomasloven/lovelace-slider-entity-row
#     type: module
#   - url: /local/vertical-stack-in-card.js # https://github.com/ofekashery/vertical-stack-in-card
#     type: module



##############
### VIEWS
##############


views:
  - title: main
    icon: mdi:home-assistant
    cards: !include views/home_screen.yaml

  - title: Lights
    icon: mdi:lightbulb
    cards: !include views/lights.yaml

  - title: Thermostat
    icon: mdi:thermometer
    cards: !include views/thermostat.yaml

  - title: Cameras
    icon: mdi:video
    cards: !include views/cameras.yaml

  - title: Livingroom
    cards: !include views/living_room.yaml


  - title: Bedroom
    cards: !include views/bedroom.yaml

  - title: Office
    cards: !include views/office.yaml

  - title: Outdoor
    cards: !include views/outdoor.yaml


  - title: Automations
    icon: mdi:home-automation
    cards: !include views/automations.yaml
