###########################
### Arduino Based Sensors
##########################



### Growing Tent Soil Moisture, Temperature and Humidity Sensor


# Growing Tent Soil Moisture Plant 1
#
# - platform: mqtt
#   state_topic: "arduino/soil1"
#   name: "Plant 1 Soil Moisture"
#   unit_of_measurement: 'MU'
#   icon: mdi:sprout
#   expire_after: 300
#   force_update: true
#
#
# # Growing Tent Soil Moisture Plant 2
#
# - platform: mqtt
#   state_topic: "arduino/soil2"
#   name: "Plant 2 Soil Moisture"
#   unit_of_measurement: 'MU'
#   icon: mdi:sprout
#   expire_after: 300
#   force_update: true


# Cold Smoker Temperature

- platform: mqtt
  state_topic: "arduino/temperature"
  name: "Cold Smoker Temperature"
  unit_of_measurement: '°C'
  device_class: temperature
  expire_after: 300
  force_update: true


# Cold SMoker Humidity

- platform: mqtt
  state_topic: "arduino/humidity"
  name: "Cold Smoker Humidity"
  unit_of_measurement: '%'
  device_class: humidity
  expire_after: 300
  force_update: true


# Cold SMoker Smoke Amount

- platform: mqtt
  state_topic: "arduino/smoke"
  unit_of_measurement: '#'
  name: "Cold Smoker Smoke Amount"
  expire_after: 300
  force_update: true
